#language: rust
#script:
#  - cd number && cargo test --all --release

language: rust
rust:
  - stable
  - nightly

os:
  - linux
  - osx

sudo: false
addons:
  apt:
    packages:
      # To build C and C++ deps
      - build-essential g++

script:
  - cd number && cargo test --all
  # link error on static libs
  - cd ../rand && cargo build --verbose --all && cargo test --all
