#language: rust
#script:
#  - cd number && cargo test --all --release

language: rust
rust:
  - stable
  - nightly

os:
  - linux
  - osx

sudo: required
addons:
  apt:
    # packages:
    #   # To build C and C++ deps
    #   - build-essential g++
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script:
  - cd number && cargo test --all --relase
  - cd ../vanity && cargo test --all --release
  # link error on static libs
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - cd ../rand && cargo cargo test --all --release
